doc: add minutes for meeting 13 Sep 2022
nodejs/package-maintenance pull request #539
Opened 2022-09-13 19:24 UTC by mhdawson

Signed-off-by: Michael Dawson <mdawson@devrus.com>

2022-09-14 16:55 UTC, zackschuster requested changes

2022-09-14 16:55 UTC, zackschuster commented on meetings/2022-09-13.md
> +* Zack Shuster
```suggestion
* Zack Schuster (@zackschuster)
```

2022-09-14 16:55 UTC, zackschuster commented on meetings/2022-09-13.md
> +  * Zak, keeping an eye on the repo, planning to do a full pass
```suggestion
  * Zack, keeping an eye on the repo, planning to do a full pass
```

2022-09-15 18:20 UTC, zackschuster approved these changes

2022-09-15 18:39 UTC, thescientist13 approved these changes

2022-09-25 07:39 UTC, Eomm approved these changes

2022-09-29 16:57 UTC, merged