feat: next steps for version management progress
nodejs/package-maintenance pull request #606
Opened 2024-07-24 22:18 UTC by wesleytodd

A discussion was had in the OpenJS Slack about how to proceeded with next steps. This PR intends to represent what the folks in that thread think should be taken as next steps.

2024-07-24 22:20 UTC, rmarkins-godaddy approved these changes

2024-07-24 22:20 UTC, GeoffreyBooth approved these changes

2024-07-24 22:29 UTC, ljharb approved these changes

2024-07-28 10:00 UTC, ovflowd approved these changes
LGTM, this is inline with what I've advised.

2024-07-28 14:23 UTC, gulbanana commented
Nice to see some progress. One minor nit: there's a potential conflict between step 2
> 2. Also on the download page, we should add instructions for installing Yarn and `pnpm` as package managers to use for a project. These instructions should follow whatever recommendation we receive from those project's maintainers.
and step 4:
> .4 Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. 

Does that mean asking Yarn and pnpm "What is your recommended installation method, as long as it isn't Corepack?"

2024-07-29 21:09 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
Let's remove this part which has not consensus – also "allow Corepack to evolve independently" is not a goal, Corepack should either be superseded or be the standard.
```suggestion
```

2024-07-29 21:27 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
> either be superseded or be the standard/recommended way to install package managers.

I think this is the main crux of the problem today right? The package manager authors do not agree on a standard way to install package managers. If they agreed, I would love that outcome but they do not.

2024-07-29 21:35 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
In any case, "allow Corepack to evolve independently" is not something anyone is asking, nor Corepack developers, nor its users.

2024-07-29 21:37 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
I guess I should say, my conclusion arriving at including 4 was that neither of these options are currently viable according to the folks who old decision making power in the respective projects. So I *agree* with you, @aduh95, that would be a much better outcome, but recognizing the reality here have arrived at number 4 being the only current way that both `corepack` and the Node.js project can reasonably both move forward in the way that is best for each project.

2024-07-30 08:45 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
I'm not talking about what would be a better outcome, I'm saying that:

- "allow Corepack to evolve independently" should not be listed here, it does not have consensus.
- "we should remove Corepack from the Node.js distribution starting in the next major release" should not be listed here, it does not have consensus.

2024-07-30 08:52 UTC, ovflowd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
> "allow Corepack to evolve independently" should not be listed here, it does not have consensus.

By whom? I assumed the decisions regarding Corepack got deferred to the package maintenance team? Isn't consensus reached even here?

We discussed briefly that Corepac could be moved to the `pkgjs` org

2024-07-30 09:07 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
If me saying "there is no consensus" is not enough to make it true, I'm not sure what would make it true. The idea of building consensus is not to restrict the list of folks we listen to, but find a compromise that everyone can get behind. "Removing Corepack from the Node.js distribution" without providing alternative is not a compromise that I can get behind, because it's not a compromise, it's a one-sided solution that does not address concerns from folks who use Corepack and would want the project to take ownership of the problems solved by Corepack.

2024-07-30 09:32 UTC, ovflowd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
Removing it from the Node.js distribution and having it be a standalone package is a solution.

Folks who want to use Corepack can install it with a binary or some other way in the future. Finding a way to bundle all sorts of package managers with their version constraints within Node.js is what feels absurd (due to it's complexity)

So far, I've been seen only drama and chaos related to anything Corepack, and as much as I love using Corepack, it feels like it is misplaced for Node.js a JavaScript runtime to try to make such decisions and encompass all package managers. In my humble opinion, Corepack should not be part of Node.

And to be fair, only you and maybe a handful of more collaborators are interested in insisting that Corepack should be part of Node. Is this a fair ask? I understand that the proposed outcome doesn't make you happy, but aren't you just a _bit_ selfish here, maybe? I don't know how we can address the Corepack issue by "consensus seeking" since you don't seem to be looking for a way of reaching a consensus.

Or so I feel after observing all Corepack-related threads for a while. Apologies for the harsh tone. It's not my intention to be harsh on you, but I genuinely don't know what else can be done here.

2024-07-30 10:23 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
We can either focus on the points that have consensus, and work on the contentious points as a follow-up – or else what is the plan here? Bully folks who express a different PoV out of the discussion? I reckon finding a compromise is hard here, because despite our best intents we have limited time and are all tired of those Corepack discussions, but in the mean time the status quo should prevail.

(And sure, I'm contributing to Node.js because I'm selfish, and incapable of consensus-seeking, whatever you say)

2024-07-30 11:02 UTC, ovflowd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
I apologize, Antoine, but my intent here is not to bully you out of the conversation nor to imply that "you contribute to Node" _because_ of being selfish nor that you are incapable of consensus-seeking. Please do not take my words out of context. That's different from my take, and I tried to be as explicit as possible to prevent misunderstandings. I'm not attacking you here; please do not take this personally. I'm just being as honest as possible here.

Truth to be told, although Corepack is part of Node core now, was that a good decision? How many people were involved in such a decision? It's always an excellent self-reflection to re-assess and verify the status quo. Again, please take my assessments with a a whole sack of salt, as I lack a lot of context here, and the least of my intent here is to attack you.

2024-07-30 13:48 UTC, lholmquist approved these changes

2024-07-30 16:09 UTC, ovflowd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
Actually, I want to invoke the TSC here to reach a consensus once and for all regarding removing Corepack from being distributed directly within Node.

I've talked with a few collaborators in DM, including Antoine, who explained his reasons for being against what we are proposing here. From what I understood, worse DX was the reason, but what I understand at the moment is that you already need to enable corepack with `corepack enable explicitly`. Moving it outside of Node allows us to install Corepack through `npx corepack` or `npm I -g corepack` or even different ways, which results in a better DX (my personal understanding) + doesn't change existing requirements of having Node (for example if using `npm`)

After reflecting on it for a bit and thinking about consensus-seeking, I do believe that Antoine might be biased as a contributor to Corepack. In light of many of us wanting to find a proper home for Corepack that allows it to shine and be decoupled from Node and its versioning, I humbly request intervention from the TSC, which has already delegated the decision-making for the future of Corepack to the Package Maintenance team.

I respect Antoine's decision to block this change. Still, I find it contradictory that we've been trying to reach a consensus for a vast, unnecessary amount of time, and I'd like to have the TSC input to decide if Antoine's decision should be overridden or not.

Apologies, Antoine for me taking this route, a desperate cry, but also a pretty standard procedure.

cc @nodejs/tsc

2024-07-30 16:22 UTC, marco-ippolito commented
Data from the latest survey, it seems corepack its pretty popular
<img width="590" alt="Screenshot 2024-07-30 at 18 21 54" src="https://github.com/user-attachments/assets/28f0350b-7d8d-4f68-99b2-5e012d48305c">

2024-07-30 16:24 UTC, ovflowd commented
> Data from the latest survey, it seems corepack its pretty popular <img alt="Screenshot 2024-07-30 at 18 21 54" width="590" src="https://private-user-images.githubusercontent.com/36735501/353538505-28f0350b-7d8d-4f68-99b2-5e012d48305c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTY5NzUsIm5iZiI6MTcyMjM1NjY3NSwicGF0aCI6Ii8zNjczNTUwMS8zNTM1Mzg1MDUtMjhmMDM1MGItN2Q4ZC00ZjY4LTk5YjItNWUwMTJkNDgzMDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE2MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NjU3ODZlNDJmNjAwZTMyMTcxNjllNzIyYWZlOWJkZjNjOWU3Yjk5MzZkM2FkMDlmMGQ1Y2Q3ZTJlMjY0ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.07RkOxdLTBqLS8VUY9fILRiQThyeCBQViVJ20khrTAQ">

It is indeed! I use it regularly too. We all love Corepack (or at least I do), I think that was never the question 🙈

2024-07-30 16:26 UTC, ljharb commented
Are we assuming tho that 2000 people can accurately represent the number of actual node users?

2024-07-30 16:27 UTC, marco-ippolito commented
> Are we assuming tho that 2000 people can accurately represent the number of actual node users?

I'm just displaying data that was gathered through an official survey, if you think the result is not relevant I guess there are other actions to take on the usefulness of the survey itself

2024-07-30 17:00 UTC, wesleytodd commented
Lets not make another massive thread of conflict here please. I am catching up on the above, but the goal here is to reset a bit, can we all try to come at this with fresh eyes?

[We have goals already listed](https://github.com/nodejs/package-maintenance/blob/main/docs/version-management/goals.md), and @aduh95 is right that "let corepack evolve independently" was not on them and we are trying to *reach* consensus including with @aduh95. And we are trying to do the above *without* having to resort to TSC involvement again until we have an internal concensys.  Lastly, having data (even if it is low volume data) is better than not having data.

So all that being said, if this is going to turn into a repeat of previous threads I am going to start hiding replies and taking a heavier hand on the direction of the conversation here.

2024-07-30 18:03 UTC, wesleytodd commented
I would encourage anyone who would like to discuss this to attend our team meeting today.

2024-07-30 18:28 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should remove Corepack from the Node.js distribution starting in the next major release. Users who wish to continue using Corepack can do so via the instructi
I do not believe this thread is "resolved", but I also believe it would be in the best interest of us all if we closed it and re-approached the question of "should point 4 stay or be dealt with after" in a new thread. There are also some other things in here we probably need to discuss, and I will work to extract it into a new set of changes to the proposal doc.

2024-07-30 20:07 UTC, wesleytodd commented
The outcome from our discussion on the call today is this:

1. We are going to adapt point 4 into a few additional steps around stages of changing our recommendation and some goals to meet at each
2. We will recommend locking the PRs and direct folks to this group for further discussion on these topics to prevent additional swirl in the ecosystem
3. We need one or more champion for Corepack to help drive this conversation. If we need to adjust meeting times or discussion forums we can do that to make it happen.

Anyone else have anything which was an action item I missed?

2024-07-30 20:14 UTC, ovflowd commented
I'll go ahead and hide my prior comments, as we have a plan moving forward, and I hope we can reach consensus seeking here! 🙇

2024-08-14 15:24 UTC, mcollina approved these changes
lgtm

2024-08-14 15:45 UTC, ronag approved these changes

2024-08-15 07:00 UTC, ShogunPanda approved these changes

2024-08-15 11:47 UTC, ruyadorno commented on docs/version-management/proposal-next-steps.md
> +2. Also on the download page, we should add instructions for installing Yarn and `pnpm` as package managers to use for a project. These instructions should follow whatever recommendation we receive f
What is the criteria behind selecting `yarn` and `pnpm` to be featured in the download page?

Were there discussions on how the decision making is going to work in case new / different package managers wants to be added there?

2024-08-15 14:08 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +2. Also on the download page, we should add instructions for installing Yarn and `pnpm` as package managers to use for a project. These instructions should follow whatever recommendation we receive f
This is a great point, and one we have not yet discussed. I think the criteria used so far was just "they are anecdotally popular". But this will not stand up over time and we need something more formal.

Do you have suggestions? 

I was thinking we likely need something about ecosystem capability but nailing down language for that is hard. For example, you could say "should be able to install packages from the npm registry and setup a functional program for most existing JS projects in the ecosystem". While I think this is a good one, I could see some folks taking issue with it and having trouble getting consensus.

I was also thinking we could use popularity as a proxy here, and just say "we will only show the top 5 most popular package installers" or something like that, but that also seems like a mine field of issues to defend.

2024-08-15 17:51 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +2. Also on the download page, we should add instructions for installing Yarn and `pnpm` as package managers to use for a project. These instructions should follow whatever recommendation we receive f
What about something like:

> package managers which node has at any point historically supported, plus others to be determined by a new policy to add and remove recommended package managers in the future.

And then we can add to our todo list to define that policy in a following PR?

I say this because to keep things moving forward, and both of those package managers were supported by `corepack` so seem like good starting points. And we do "pick winners" so it seems reasonable that we could just say "come to the PMWG to propose a new one, if you can get a consensus recommendation we will add it". It is not strict or clear, but it is seemingly reasonable imo.

2024-08-15 18:31 UTC, ruyadorno commented on docs/version-management/proposal-next-steps.md
> +2. Also on the download page, we should add instructions for installing Yarn and `pnpm` as package managers to use for a project. These instructions should follow whatever recommendation we receive f
yeah, adding that part sounds like a good solution for now so that it doesn't prevent progress 👍

2024-08-17 16:10 UTC, wesleytodd commented
Ok, I (finally) pushed some amendments based on our previous conversations. It is not exactly the feedback I got from @aduh95 or @ruyadorno but I think I captured the spirit of our conversations. Feedback welcome!

2024-08-17 18:04 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +2. Also on the download page, we should add instructions for installing package managers which node has at any point historically supported (Yarn and `pnpm), plus any others to be determined by a new
```suggestion
2. Also on the download page, we should add instructions for installing package managers which node has at any point historically supported (Yarn and `pnpm`), plus any others to be determined by a new policy (yet to be proposed) to add and remove recommended package managers. These instructions should follow whatever recommendation we receive from those projects' maintainers.
```

2024-08-17 18:36 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +5. Corepack governence and maintenence will be relinquished to the Corepack team who can decide on next steps for the project.
I find the phrasing “relinquished to the Corepack team” not very clear, arguably Corepack governance and maintenance are already handled by the Corepack team. I think what we should say is something like:
```suggestion
5. At that point, Corepack would no longer serve a purpose in Node.js project, so its repository will either be archived or transferred.
```

2024-08-17 21:26 UTC, ruyadorno approved these changes

2024-08-17 21:35 UTC, anonrig commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
Is the "removal" decision already made?

2024-08-17 22:04 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +3. Corepack's documentation should be moved out of the Node.js API documentation and into its own website, or accessible as Markdown files in the Corepack repo. Corepack is a separate project from No
```suggestion
3. Corepack's documentation should be moved out of the Node.js API documentation and into its own website, or accessible as Markdown files in the Corepack repo. Corepack is a separate project from `node` and intermingling its documentation within `node`'s is confusing; we don't do that for `npm` even though we distribute `npm`.
```

2024-08-17 22:15 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
I'm not sure the goal is to "make a decision", but rather to find a plan that can have consensus. If you have objections, or alternative proposals that you think more likely to get consensus, now's the best time to speak!

2024-08-17 22:46 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +5. Corepack governence and maintenence will be relinquished to the Corepack team who can decide on next steps for the project.
I was trying to make less strong of a stance, but as long as you are alright with this phrasing I am fine with it. Lets maybe leave this open and get a bit of feedback from people on it?

2024-08-18 01:44 UTC, anonrig commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
This line makes the decision of removing corepack from node.js. There is no discussion here unless I object. Is that correct?

2024-08-18 23:41 UTC, anonrig requested changes
I have had some tough time writing this, and be the representative of users of corepack, but unfortunately, if I don't, this pull-request will probably land.

Hence, I'd like to "request for review". Please read my comments with goodwill and know that English is my second language, and my choice of words might not be correct all time. 

----

I left a comment at https://github.com/nodejs/package-maintenance/pull/606#discussion_r1720870473, asking about the decision to remove corepack. 

I haven't had any chance/time to attend any of the meetings, but I don't think this decision is beneficial for the common good of the community. Removing a highly used feature is almost always result in backlash. 

I honestly don't think this is not the correct place/method/way/approach to make a final decision (or stating/hinting/commenting/indicating) that we are preparing to remove a feature from Node.js. We have a governing body to make the final decision about any discrepancies.

If the common consensus is to remove corepack, I'd like to proceed with a TSC voting where all votes are visible to the community. If this is not the preferred way, I would like to ask a public voting from all collaborators and make this decision together. 

This is important for preserving history.

2024-08-18 23:52 UTC, ovflowd commented
> I have had some tough time writing this, and be the representative of users of corepack, but unfortunately, if I don't, this pull-request will probably land.
> 
> Hence, I'd like to "request for review". Please read my comments with goodwill and know that English is my second language, and my choice of words might not be correct all time. 
> 
> ----
> 
> I left a comment at https://github.com/nodejs/package-maintenance/pull/606#discussion_r1720870473, asking about the decision to remove corepack. 
> 
> I haven't had any chance/time to attend any of the meetings, but I don't think this decision is beneficial for the common good of the community. Removing a highly used feature is almost always result in backlash. 
> 
> I honestly don't think this is not the correct place/method/way/approach to make a final decision (or stating/hinting/commenting/indicating) that we are preparing to remove a feature from Node.js. We have a governing body to make the final decision about any discrepancies.
> 
> If the common consensus is to remove corepack, I'd like to proceed with a TSC voting where all votes are visible to the community. If this is not the preferred way, I would like to ask a public voting from all collaborators and make this decision together. 
> 
> This is important for preserving history.

The TSC already had made a vote deferring decisions regarding Corepack to this WG... I genuinely don't know what should be done then.

I think you are more in your right to be against this change and I respect you for that. But I don't think it is semantically correct to say that doing X or Y is wrong or right; These are all subjective opinions and we are doing these changes based on the best of our knowledge and intends. (I might be wrong tho)

2024-08-18 23:56 UTC, anonrig commented
There is a pending/draft TSC voting about corepack which is still alive. https://github.com/nodejs/TSC/pull/1527

2024-08-18 23:56 UTC, ljharb commented
Adding corepack just had a TSC vote, why would removing it need a full collaborator vote?

2024-08-18 23:57 UTC, ovflowd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
No, I believe you misunderstood. But I think @wesleytodd made updates to this paragraph to better describe that landing this PR != removing Corepack from Node.js

We don't have that power.

2024-08-19 00:00 UTC, anonrig commented
> Adding corepack just had a TSC vote, why would removing it need a full collaborator vote?

Adding corepack is not the topic of this pull-request. There is no "need". Your choice of words does not reflect what I was trying to say, and steers the conversation to a place where I don't feel comfortable in. 

I merely recommended a collaborator vote since it is a highly used feature of node.js and community clearly doesn't want it to be removed.

2024-08-19 00:01 UTC, ovflowd commented
For community members and core collaborators that are coming without context here, I'd recommend to read the actual proposed changes on the "File changes" tab, before quickly reacting negatively to this PR 😅

2024-08-19 00:05 UTC, ovflowd commented
> > Adding corepack just had a TSC vote, why would removing it need a full collaborator vote?
> 
> Adding corepack is not the topic of this pull-request. There is no "need". Your choice of words does not reflect what I was trying to say, and steers the conversation to a place where I don't feel comfortable in. 
> 
> I merely recommended a collaborator vote since it is a highly used feature of node.js and community clearly doesn't want it to be removed. 

But Yagiz, this PR (on its current state) is not attempting to remove Corepack. Could you give a 2nd 👀 on the changeset and double check if the wording is wrong?

2024-08-19 00:09 UTC, anonrig commented
> But Yagiz, this PR (on its current state) is not attempting to remove Corepack. Could you give a 2nd 👀 on the changeset and double check if the wording is wrong?

Particularly the following line hints me towards the decision thats being held and steers the conversation to a specific place. If the goal of this pull-request is to recommend changes, it should cover all possible cases, including the possibility of not removing corepack and should avoid definitive/assertive wording like "we should prepare" where the thing we "should" do, is not definitive. 

> "Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution"

2024-08-19 00:31 UTC, needim commented
I support separating Corepack from Node.js, but I have concerns about the potential disruption for those who rely on it in CI/CD pipelines. A well-planned transition is essential to avoid issues.

Additionally, I'd love to see Corepack evolve with features similar to NVM or Volta, improving version management and overall developer experience. Clear branding and a focus on DX could help spread Corepack's name and increase adoption. It should be a tool that allows developers to think less and focus more.

2024-08-19 02:35 UTC, Spitfire1900 commented
This is coming as a take from a primarily Python developer.

The Node ecosystem needs to take a hard look at the future Python had fairly well adopted at this point (though there are stragglers) of PEP 518, and the idea that `pip install` ing a package that requires a different build tool is automatically resolved and built with the `build.requires` metadata that the PEP provides.

Notably I highlight this because the Python ecosystem elected to build this capability directly into pip, the standard package manager for Python.

I am not saying the corepack is the long term answer, but moving further away from an OOTB ability to do accomplish the similitude goals that PEP 518 and corepack have is not.

In a potentially bold stance, perhaps npm should adopt the major features of corepack directly, as an emulation of the `pip install .` experience.

2024-08-19 04:24 UTC, ovflowd commented
> > But Yagiz, this PR (on its current state) is not attempting to remove Corepack. Could you give a 2nd 👀 on the changeset and double check if the wording is wrong?
> 
> Particularly the following line hints me towards the decision thats being held and steers the conversation to a specific place. If the goal of this pull-request is to recommend changes, it should cover all possible cases, including the possibility of not removing corepack and should avoid definitive/assertive wording like "we should prepare" where the thing we "should" do, is not definitive. 
> 
> > "Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution"

Yes, but the wording (maybe here's your English-non fluency coming in, but it could also be a mis-interpretation from my side) that:

"Once all of the above is complete, we should prepare the **eventual** removal of Corepack from the Node.js distribution"

This line keeps it clear that the goal is to find possible alternatives but it isn't stating that the removal is concrete or will happen, and all the other steps 1-4 are also extremely relevant.

2024-08-19 05:08 UTC, gulbanana commented
If the goal is not to remove corepack, why would any of the changes be necessary?

2024-08-19 06:52 UTC, mcollina commented
@anonrig please open a separate issue to discuss the governance of the project (in admin or tsc). What you are asking is outside of our charter for a lot of reasons.

---

On the topic:

> I haven't had any chance/time to attend any of the meetings, but I don't think this decision is beneficial for the common good of the community. Removing a highly used feature is almost always result in backlash.

My take is that solving https://github.com/nodejs/corepack/issues/495 will require a _redesign_ of corepack, almost from scratch. So far, _no one_ has been willing to address the problem, and there has been a light push back on it.

(I personally have no time for it, but I'll be ok in a brainstorming session and reviewing a design document for such a redesign).

The security implications of https://github.com/nodejs/corepack/issues/495 alone would not be _enough_ to justify removal (even if it's an experimental feature), but combined with the lack of volunteers/pushback to do the required work, I see no other path forward.

As @targos once said: corepack could be what we want. Despite bing a popular feature, and _many_ tweets, blog posts and videos discussing this, I see no volunteers to do the work needed: and most people commenting on this have the skills to participate.

What you are asking is for the TSC to take on the maintenance of corepack, and the answer is (likely) a "no". No one can force a volunteer to do what they don't want to do.

2024-08-19 07:08 UTC, gulbanana commented
I'm afraid you've mischaracterised the issue. After reading through https://github.com/nodejs/corepack/issues/495, it appears that people don't agree on whether there's a problem to be solved, or what the solution would be. It's not that there's a lack of labour available, it's that not everyone shares your perspective that `yarnpkg.com` is more of a security risk than `npmjs.com`.

2024-08-19 07:10 UTC, ovflowd commented
> If the goal is not to remove corepack, why would any of the changes be necessary?

This issue also entails better documentation for Corepack, a dedicated website and it being included on the downloads page, among other things.

2024-08-19 07:12 UTC, gulbanana commented
> This issue also entails better documentation for Corepack, a dedicated website and it being included on the downloads page, among other things.

It doesn't need a dedicated website or a download page link if it's part of Node's documentation and included in the Node installation - as is currently the case. I'm not saying it's wrong to remove corepack, if that's what the project wants to do, but it's silly to carry out this process if it isn't a foregone conclusion.

2024-08-19 07:14 UTC, ovflowd commented
> I'm afraid you've mischaracterised the issue. After reading through https://github.com/nodejs/corepack/issues/495, it appears that people don't agree on whether there's a problem to be solved, or what the solution would be. It's not that there's a lack of labour available, it's that not everyone shares your perspective that `yarnpkg.com` is more of a security risk than `npmjs.com`.

That is one of the issues. My understanding is also that there's no agreement whatsoever on what Corepack should be or not, how it should work; And pretty much most of the proposals/initiatives related to it got pushback.

So, it's regarding multiple facets -- from people working on it for longterm, getting a solution all agree on, and ensuring its long term maintenance, and that's where the issue lies. Since as it stands it has potential security threats, to be honest, that'd not _my_ take on it. But take my comments with 2 grains of salt :)

2024-08-19 07:14 UTC, gulbanana commented
"How corepack should work is a controversial question" could be sufficient reason to abandon it, but, again, it'd be better to actually make that call explicitly.

2024-08-19 07:15 UTC, ovflowd commented
> It doesn't need a dedicated website or a download page link if it's part of Node's documentation and included in the Node installation - as is currently the case.

It does. Because it is not a Node module, hence it probably does not belong within the Node API docs. NPM has its own website and docs page. I'm not sure why you are arguing about these points.

2024-08-19 07:17 UTC, gulbanana commented
> It does. Because it is not a Node module, hence it probably does not belong within the Node API docs. NPM has its own website and docs page. I'm not sure why you are arguing about these points.

I am objecting to the process, which seems intended to reverse a previously-made decision without ever admitting to doing so. Just say the corepack experiment has failed (if people agree that it has). Claiming that it was never part of node is nonsense; it was, and still is, until now.

2024-08-19 07:17 UTC, ovflowd commented
> If the TSC wants to reverse its decision to include corepack in Node that's perfectly legitimate. But in that case it should actually do so, rather than refusing to make a decision

My understanding is that they made a decision, and the decision was to delegate to this group... That is a decision; But I was not involved not I understand/are aware of what exactly was decided or not back then. I'm just repeating what I was told.

2024-08-19 07:18 UTC, ovflowd commented
Anyhow, this is getting off-topic, @gulbanana, could you please move this to a discussions page; You are making a lot of guesses (as am I) and I rather leave the PR clean for reviews.

2024-08-19 07:18 UTC, gulbanana commented
Sure, I'll avoid further commentary.

2024-08-19 07:20 UTC, ovflowd commented
> > It does. Because it is not a Node module, hence it probably does not belong within the Node API docs. NPM has its own website and docs page. I'm not sure why you are arguing about these points.
> 
> 
> 
> I am objecting to the process, which seems intended to reverse a previously-made decision without ever admitting to doing so. Just say the corepack experiment has failed (if people agree that it has). Claiming that it was never part of node is nonsense; it was, and still is, until now.

Sorry but you cannot object to it, or at least not formally.

I don't think Corepack has failed at all, it is popular and well used (by myself included).

It is not part of the Node "api" it is not a module built-in to the  Node binary, hence why it (imo) does not belong to the Node docs, of the binary itself.

Even Undici is getting its own docs page and it is part of Node.

2024-08-19 07:21 UTC, ovflowd commented
> Sure, I'll avoid further commentary.

Thanks. Ill hide our off-topic messages, then.

2024-08-19 10:50 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
The premise of this discussion is "Node.js will outlive Corepack", and so the question we're trying to answer is "How can we make it happen in way that maximises everyone's happiness?". If really, you don't see a future for Node.js without Corepack, that's a bummer, but maybe for the sake of the discussion, it's still worth discussing.
IMO Corepack is nothing special, we're more than capable of coming up an alternative that would provide the same DX (or similar enough), also covers Node.js versioning, and ideally would not require getting approval or work from package manager maintainers (which are busy people). If such alternative is able to get consensus, it would make Corepack de facto obsolete; so what's important now is to gather the potential points of contention (surely it's not whether that potential tool is named "Corepack").

2024-08-19 15:43 UTC, wesleytodd commented
The goal of this was to work toward a proposal which could reach consensus. @anonrig I think a bunch of your comments are valid and relevant, but it appears they have caused this discussion to spiral out of control again. I said it above and I mean it, please dont make this a thread where I have to start hiding comments (thanks to whoever did it with the ones above, that was exactly the kind of thing I was worried about). If folks want to argue please come to our meetings or join us in the slack discussions. This PR is not a vote, landing this PR does not constitute a decision by the TSC to take a specific action, and so a blocking review on it does nothing of consequence.

> We have a governing body to make the final decision about any discrepancies.

With the above being said, the TSC has failed multiple times to reach a consensus. The whole point here is to push it back *OUT* of the voting realm until there is a vote which actually has a chance of success. If you disagree with that approach, I am not sure how to convince you, but it staying in limbo with compeeting PRs to enable and remove it entirely is not healthy for the project, community, or the TSC itself.

And lastly, that governing body TOOK A VOTE to decide to give this group the authority to make a recommendation after a proper community discussion. That is what resulted in this PR. So if we could bring it back (or as @mcollina said, open a different issue to discuss other governance issues) to the topic of this PR that would be great.

> There is a pending/draft TSC voting about corepack which is still alive.

One of our discussed recommendations (which did not get included in the PR content) above was that we close all lock all these for now until we can sort our a consensus recommendation here. Do you think I need to add that to the text of this PR?

https://github.com/nodejs/package-maintenance/pull/606#issuecomment-2259121561

> I genuinely don't know what should be done then if there's a -1 on this PR. Should another vote happen?

No, working groups do not have votes like this afaik. We work toward consensus or we decide to abandon the recommendation. So if @anonrig wants to join the group and help us refine this until there is consensus that would be awesome, if not I don't think we are ready to kick it back up to another ill fated TSC vote.

---

@Spitfire1900 I hid your comment as off topic. Sorry, but please we are not seeking recommendations like this at this time. We would be happy to hear this feedback in a separate issue or in one of our meetings as I think it is great feedback. We just need to be ruthless in keeping this discussion on track because of how often it has went off into the weeds.

Similarly I hid the discussions with @anonrig and @ljharb about the unrelated proposed governance issues. 

---

In closing, I would love if we could get feedback on the [goals we stated](https://github.com/nodejs/package-maintenance/blob/main/docs/version-management/goals.md). If you disagree with those goals, that would be good to hear because this proposal is just a continuation of achieving those goals.

2024-08-19 15:53 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
@anonrig Am I correct that this line is your primary concern? After the discussion in the main thread, do you have a recommendation to change this line which would resolve your issues? What about something like:

```suggestion
4. Once all of the above is complete, we should start recommending alternative workflows to reduce the churn if/when we decide to remove `corepack` from the Node.js distribution. Users who wish to continue using Corepack will be recommended to do so via the instructions available on the Node.js download page or in Corepack's documentation.
```

2024-08-19 16:38 UTC, stephenwade commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
**suggestion:**

> this PR (on its current state) is not attempting to remove Corepack.

> We don't have that power.

"if/when we decide to remove `corepack`" still reads to me as "eventually we want to remove Corepack" (which makes me interpret the PR as "this is our plan to get rid of Corepack"). So I feel that the text of @wesleytodd's suggestion is still somewhat at odds with the comments I quoted above.

For anyone reading the diff rather than all the comments, I believe this wording change would make clear that this PR is not trying to remove Corepack but is simply recommending improvements for Node package/version management in general.

```suggestion
4. Once all of the above is complete, we should start recommending alternative workflows in case Corepack is removed from the Node.js distribution. Users who wish to continue using Corepack will be recommended to do so via the instructions available on the Node.js download page or in Corepack's documentation.
```

2024-08-19 16:39 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
I am perfectly comfortable with this new wording if that achieves agreement to keep the conversation moving forward.

2024-08-19 17:34 UTC, aduh95 commented on docs/version-management/proposal-next-steps.md
> +5. Corepack governence and maintenence will be relinquished to the Corepack team who can decide on next steps for the project.
I guess we could remove that step altogether, as I said, the Corepack team is already in charge of the governance and maintenance of Corepack, so that step is not adding much.
```suggestion
```

2024-08-20 23:52 UTC, fungilation commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
remove head from ass or remove npm from world

this debate and PR staying open on eventual removal of corepack which is clearly used by community, is a waste of time from the get go, and a showcase on how out of touch and misprioritized Node.js has gotten

politicized wordsmithing, really?

2024-08-21 01:01 UTC, lukaselmer commented
@wesleytodd 

> In closing, I would love if we could get feedback on the [goals we stated](https://github.com/nodejs/package-maintenance/blob/main/docs/version-management/goals.md). If you disagree with those goals, that would be good to hear because this proposal is just a continuation of achieving those goals.

IMO the goals are a great start. Maybe they need to be clearer.

> Define the correct Node.js runtime version and package manager version for projects.

This means that the package manager _and_ the version of the package manager can be specified, right? Not only the version of npm 😏 

> Install Node.js and a package manager for a local development environment.
> Run the correct version of Node.js and of a package manager for each project.

From these two points, I'm missing that this should be as easy as possible, and mostly (fully?) automated. A website/manual with instructions is not good enough.

2024-08-21 01:31 UTC, anonrig commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
I'm comfortable with @stephenwade's recommendation as well

2024-08-21 13:17 UTC, wesleytodd commented on docs/version-management/proposal-next-steps.md
> +4. Once all of the above is complete, we should prepare the eventual removal of Corepack from the Node.js distribution by recommending alternative workflows. Users who wish to continue using Corepack
Perfect. Committed that, are you willing to move your change requested review to an approval?

2024-08-21 13:31 UTC, aduh95 approved these changes

2024-08-21 13:52 UTC, ovflowd commented
@anonrig are you willing to change your "request for changes" to approval, given what @wesleytodd mentioned?

2024-08-21 13:59 UTC, wesleytodd commented
Awesome. We have addressed all the concrete feedback. Thanks everyone who is helping move this conversation forward, your great work is very helpful.

2024-08-21 13:59 UTC, merged